### ISSUE TITLE
Not sure how to actually run it

### ISSUE THREAD

**Issue by quietmansoath** [AnsgarKlein/GPG-Gui#3]
Appreciate you making this, but if the program is made for beginners, presumably there should be more hand-holding on how to install and run everything. On pop os with kde plasma 20.10, got everything downloaded and presumably installed, but I have no idea how to run this.

**Comment by AnsgarKlein** [comment]
Hi quietmansoath,

thank you for your feedback! I've added more details on how to compile and install to the README.
Basically it comes down to:

```bash
meson setup build
ninja -C build
sudo ninja -C build install
```

After that *GPG-Gui* should be installed system-wide and you should be able to start it with `gpg-gui`. A *GPG-Gui* entry should also appear in your KDE application menu.

Regarding more hand holding:
I'm planning on automatically creating .rpm and .deb packages for each release as well as creating a flatpak. That should make it much easier to install GPG-Gui without manually compiling from source. Unfortunately it's not done yet.

If you need any more assistance feel free to ask

**Comment by quietmansoath** [comment]
Thanks so much for your help! Unfortunately I downloaded all of the dependencies from my package manager, but I still can't get it to work. I think I'll just keep an eye on that .deb package.

**Comment by AnsgarKlein** [comment]
Hi quietmansoath,
the latest release v0.2.2 includes native packages for Ubuntu 18.04, Ubuntu 20.04, Debian 10, Fedora 33.

You said you are using PopOS 20.10, which is based on Ubuntu 20.10. Unfortunately I only create packages for LTS versions of Ubuntu, but the package for Ubuntu 20.04 should probably work fine.
You can find the .deb package on the [release page for v0.2.2](https://github.com/AnsgarKlein/GPG-Gui/releases/tag/v0.2.2).

Please let me know if you have any trouble
